### ISSUE TITLE
hln: File exists -- If the target directory already exists, what about creating a link in that directory?

### ISSUE THREAD

**Issue by wangguoqin1001** [selkhateeb/hardlink#24]
Like the behavior in ln, if the target directory already exists, then create a link in that directory instead, to make the following command work:

ln ~/blablabla .

**Comment by askaliuk** [comment]
+1

**Comment by BenjaminHCCarr** [comment]
@connorworley  has a `PR` for this selkhateeb#29

it also does the sane thing of just creating the link in `.` if no destination is specified.

**Comment by selkhateeb** [comment]
I just merged in @connorworley PR. Closing this.
