### ISSUE TITLE
Does this work under Yosemite?

### ISSUE THREAD

**Issue by retrography** [selkhateeb/hardlink#25]
I can't create a hardlink, even when I log in as root (which is normally disabled on MacOS and is a member of "wheel" with full administrative and system rights). I have checked all the hardlink conditions, yet I still receive an "operation not permitted" error.

**Comment by selkhateeb** [comment]
I'm not sure. I don't have Yosemite.
Thanks

**Comment by retrography** [comment]
I could finally make it work, so it does work. The mistake was mine.

**Comment by selkhateeb** [comment]
Thanks for your update.

On Thu, Feb 5, 2015 at 7:57 PM, retrography <notifications@github.com>
wrote:

> I could finally make it work, so it does work. The mistake was mine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/selkhateeb/hardlink/issues/25#issuecomment-73168313>.
>



-- 
Thanks
Sam Elkhateeb
NanoSN Cloud Computing Service Inc.
