### ISSUE TITLE
A way to determine which files are hard links?

### ISSUE THREAD

**Issue by starbuck451** [selkhateeb/hardlink#26]
I created hardlinks in a directory and now I'm struggling to remember which are hard links and which are in fact the files themselves.

**Comment by jamespayne** [comment]
http://superuser.com/questions/12972/how-can-you-see-the-actual-hard-link-by-ls Maybe what you are looking for? There seems to be some heated debate about this in that post.

**Comment by starbuck451** [comment]
Thanks for that James, that's what I was looking for, good work on your project.

**Comment by jamespayne** [comment]
No worries, I haven't really contributed to the project. I just use it. Full credit should go to @selkhateeb
